### ISSUE TITLE
are you going to add support for the thumbnail.get method?

### ISSUE THREAD

**Issue by ryankshaw** [scribd/rscribd#1]
hi, I'd love to be able to use the thumbnail.get method from scribd's api, but I dont see it implemented with this library, are you planning on it?
see:
http://www.scribd.com/developers/api?method_name=thumbnail.get

thanks,
Ryan

**Comment by RISCfuture** [comment]
Just did it -- 873bd722c4334d8505a984431678b6fc9399c978

**Comment by ryankshaw** [comment]
sweet, thanks.  looks good.
