### ISSUE TITLE
User.login error

### ISSUE THREAD

**Issue by tsailipu** [scribd/rscribd#7]
Just ran into this of what otherwise has been an error-free operation for years.  Is there something up on Scribd side or this is due to something on my end (library upgrade perhaps? but i can't think of any...).  I am using rscribd 1.3.0 and ruby 1.8.7.

REXML::ParseException: #<REXML::ParseException: Missing end tag for 'img' (got "div")
Line: 
Position: 
Last 80 unconsumed characters:
        </div>                  <script type="text/java>
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/parsers/baseparser.rb:330:in `pull'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/parsers/treeparser.rb:22:in`parse'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/document.rb:227:in `build'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/document.rb:43:in`initialize'
/Library/Ruby/Gems/1.8/gems/rscribd-1.3.0/lib/scribd/api.rb:138:in `new'
/Library/Ruby/Gems/1.8/gems/rscribd-1.3.0/lib/scribd/api.rb:138:in`send_request'
/Library/Ruby/Gems/1.8/gems/rscribd-1.3.0/lib/scribd/user.rb:175:in `login'
(irb):4:in`irb_binding'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb/workspace.rb:52:in `irb_binding'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb/workspace.rb:52
...
Missing end tag for 'img' (got "div")
Line: 
Position: 
Last 80 unconsumed characters:
        </div>                  <script type="text/java
Line: 
Position: 
Last 80 unconsumed characters:
        </div>                  <script type="text/java
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/parsers/treeparser.rb:92:in`parse'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/document.rb:227:in `build'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/document.rb:43:in`initialize'
    from /Library/Ruby/Gems/1.8/gems/rscribd-1.3.0/lib/scribd/api.rb:138:in `new'
    from /Library/Ruby/Gems/1.8/gems/rscribd-1.3.0/lib/scribd/api.rb:138:in`send_request'
    from /Library/Ruby/Gems/1.8/gems/rscribd-1.3.0/lib/scribd/user.rb:175:in `login'
    from (irb):4

**Comment by snowmaker** [comment]
Hi Phil,

That's cause you're getting a 500 page from Scribd.  What's the exact URL
you are requesting from the API?  You may need to add a puts statement or
similar to print it out.

Jared

On Tue, May 1, 2012 at 11:59 PM, Philip L.Tsai <
reply@reply.github.com

**Comment by tsailipu** [comment]
I guess Scribd API site was undergoing maintenance late last night PDT.  The same operation now works without any error.

The operation is simply: Scribd::User.login(username, password).  The exact sequence is:

require 'rscribd'
Scribd::API.instance.key = [key]
Scribd::API.instance.secret = [secret]
Scribd::User.login(username, password)
